one = 'one'
two = 'two'
game = 'game'
only = 'only'
semi = 'semi'
auto = 'auto'
name = 'name'
data = 'data'
sight = 'sight'
color = 'color'
point = 'point'
index = 'index'
speed = 'speed'
count = 'count'
armed = 'armed'
empty = 'empty'
stock = 'stock'
stand = 'stand'
squat = 'squat'
prone = 'prone'
weapon = 'weapon'
region = 'region'
points = 'points'
muzzle = 'muzzle'
switch = 'switch'
bullet = 'bullet'
active = 'active'
backpack = 'backpack'
foregrip = 'foregrip'
attitude = 'attitude'
firemode = 'firemode'
interval = 'interval'
ballistic = 'ballistic'

# 检测数据
detect = {
    "3440.1440": {
        backpack: (936, 78, 80, 40),  # 检测背包是否打开的位置
        weapon: {
            region: (2212, 125, 632, 577),  # 一二号武器全截图
            one: {
                index: 1,
                point: (16, 20),  # (y, x), 判断一号武器是否存在的点(纯白色)
                name: (42, 0, 260, 42),
                sight: (365, 29, 62, 31),
                muzzle: (2, 207, 62, 62),
                foregrip: (138, 207, 62, 62),
                stock: (568, 207, 62, 62),
            },
            two: {
                index: 2,
                point: (319, 18),  # (y, x), 判断二号武器是否存在的点(纯白色)
                name: (42, 308, 260, 42),
                sight: (365, 335, 62, 31),
                muzzle: (2, 514, 62, 62),
                foregrip: (138, 514, 62, 62),
                stock: (568, 514, 62, 62),
            },
            name: {
                769: 'ACE32',
                561: 'AKM',
                511: 'AUG',
                1269: 'Beryl M762',
                716: 'G36C',
                568: 'Groza',
                309: 'K2',
                794: 'M16A4',
                646: 'M416',
                1360: 'Mk47 Mutant',
                552: 'QBZ',
                798: 'SCAR-L',
                669: 'Mini14',
                602: 'Mk12',
                588: 'Mk14',
                597: 'QBU',
                494: 'SKS',
                1627: 'SLR',
                464: 'VSS',
                636: 'Crossbow',
                715: 'DP-28',
                710: 'M249 ',
                605: 'MG3',
                846: 'Mortar',
                1325: 'Panzerfaust',
                564: 'DBS',
                423: 'O12',
                556: 'S12K',
                758: 'S1897',
                737: 'S686',
                647: 'AWM',
                872: 'Kar98k',
                993: 'Lynx AMR',
                513: 'M24',
                1611: 'Mosin Nagant',
                740: 'Win94',
                934: 'Micro UZI',
                742: 'MP5K',
                608: 'MP9',
                559: 'P90',
                1207: 'PP-19 Bizon',
                1567: 'Tommy Gun',
                880: 'UMP45',
                624: 'Vector',
                1917: 'Blue Chip Detector',
                1553: 'Drone Tablet',
                1664: 'EMT Gear',
                843: 'Spotter Scope',
                947: 'Tactical Pack',
            },
        },
        attitude: {  # 姿态识别
            region: (1374, 1312, 66, 59),
            stand: [(37, 33), (37, 28), (17, 28), (20, 17)],  # (y, x), 纯黑色
            squat: [(19, 39), (20, 51), (36, 13), (41, 28)],
            prone: [(33, 48), (34, 60), (39, 25), (41, 18)],
        },
        firemode: {  # 武器模式识别
            region: (1649, 1331, 27, 31),
            points: [(3, 13), (8, 13), (14, 13), (19, 13)]
        },
        bullet: (1712, 1324),  # 纯红色则没有子弹
        active: {  # 识别当前使用的武器序号
            region: (2810, 1250, 240, 153),
            one: {  # 主界面右下角一号武器展示位
                # region: (0, 89, 207, 65),
                region: (0, 112, 207, 1),
                1: [(98, 217), (98, 215), (100, 217), (102, 217), (104, 217), (106, 217)],  # 一号武器展示位展示1号武器
                2: [(99, 215), (97, 215), (97, 217), (97, 219), (97, 217), (102, 217), (106, 215), (106, 220)],  # 一号武器展示位展示2号武器
            },
            two: {
                # region: (0, 10, 207, 65),
                region: (0, 33, 207, 1),
                2: [(20, 215), (18, 215), (18, 217), (18, 219), (20, 219), (22, 219), (27, 215), (27, 220)],  # 主界面右下角二号武器展示位
            },
        },
    },
    "2560.1440": {

    },
    "2560.1080": {

    },
    "1920.1080": {

    }
}

# 翻译数据
translation = {
    'ACE32': 'ACE32',
    'AKM': 'AKM',
    'AUG': 'AUG',
    'Beryl M762': 'Beryl M762',
    'G36C': 'G36C',
    'Groza': 'Groza',
    'K2': 'K2',
    'M16A4': 'M16A4',
    'M416': 'M416',
    'Mk47 Mutant': 'Mk47 Mutant',
    'QBZ': 'QBZ',
    'SCAR-L': 'SCAR-L',
    'Mini14': 'Mini14',
    'Mk12': 'Mk12',
    'Mk14': 'Mk14',
    'QBU': 'QBU',
    'SKS': 'SKS',
    'SLR': '自动装填步枪',
    'VSS': 'VSS',
    'Crossbow': '十字弩',
    'DP-28': 'DP-28',
    'M249 ': 'M249 ',
    'MG3': 'MG3',
    'Mortar': '迫击炮',
    'Panzerfaust': '铁拳火箭筒',
    'DBS': 'DBS',
    'O12': 'O12',
    'S12K': 'S12K',
    'S1897': 'S1897',
    'S686': 'S686',
    'AWM': 'AWM',
    'Kar98k': 'Kar98k',
    'Lynx AMR': 'Lynx AMR',
    'M24': 'M24',
    'Mosin Nagant': '莫辛纳甘步枪',
    'Win94': 'Win94',
    'Micro UZI': '微型 UZI',
    'MP5K': 'MP5K',
    'MP9': 'MP9',
    'P90': 'P90',
    'PP-19 Bizon': 'PP-19 Bizon',
    'Tommy Gun': '汤姆逊冲锋枪',
    'UMP45': 'UMP45',
    'Vector': 'Vector',
    'Blue Chip Detector': '蓝色晶片探测器',
    'Drone Tablet': '无人机控制器',
    'EMT Gear': '应急处理装备',
    'Spotter Scope': '观测镜',
    'Tactical Pack': '战术背包',
    'Angled Foregrip': '直角前握把',
    'Haalfgrip': '半截式握把',
    'Laser Sight': '激光瞄准器',
    'Lightweight Grip': '轻型握把',
    'Quiver': '箭袋',
    'Thumbgrip': '拇指握把',
    'Vertical Foregrip': '垂直握把',
    'Choke SG': '扼流圈',
    'Compensator AR': '后座补偿器',
    'Compensator SMG': '枪口补偿器',
    'Compensator SR': '后座补偿器',
    'Duckbill SG': '鸭嘴枪口',
    'Flash Hider AR': '消焰器',
    'Flash Hider SMG': '消焰器',
    'Flash Hider SR': '消焰器',
    'Suppressor AR': '消音器',
    'Suppressor SMG': '消音器',
    'Suppressor SR': '消音器',
    '15x Scope': '15x镜',
    '2x Scope': '2x镜',
    '3x Scope': '3x镜',
    '4x Scope': '4x镜',
    '6x Scope': '6x镜',
    '8x Scope': '8x镜',
    'Holographic Sight': '全息',
    'Red Dot Sight': '红点',
    'Bullet Loops': '子弹袋',
    'Cheek Pad': '托腮板',
    'Folding Stock': '折叠式枪托',
    'Heavy Stock': '重型枪托',
    'Tactical Stock': '战术枪托',
}

# 武器数据, 在列表中的武器才会执行压制
weapons = {
    'M416': {
        interval: 85,  # 全自动射击间隔
        attitude: {  # 姿态影响因子
            stand: 1,
            squat: 0.75,
            prone: 0.5,
        },
        sight: {  # 瞄具影响因子
            '2x Scope': 1.9,
            '3x Scope': 3,
            '4x Scope': 4,
            '6x Scope': 6,
            'Holographic Sight': 1,
            'Red Dot Sight': 1,
        },
        muzzle: {  # 枪口影响因子
            'Compensator AR': 0.78,
            'Flash Hider AR': 0.87,
            'Suppressor AR': 1,
        },
        foregrip: {  # 握把影响因子
            'Angled Foregrip': 1,
            'Haalfgrip': 0.8,
            'Laser Sight': 1,
            'Lightweight Grip': 0.92,
            'Thumbgrip': 0.92,
            'Vertical Foregrip': 0.77,
        },
        stock: {  # 枪托影响因子
            'Heavy Stock': 0.9,
            'Tactical Stock': 0.965,
        },
        ballistic: [36, 23, 24, 23, 33, 34, 34, 34, 40, 40, 40, 40, 41, 41, 41, 42, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 50, 51, 50, 51, 50, 50, 50]
    },
    "ACE32": {
        "ballistic": [
            30,
            30,
            30,
            30,
            40,
            40,
            40,
            40,
            46,
            46,
            46,
            46,
            49,
            49,
            49,
            49,
            56,
            56,
            56,
            56,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58
        ],
        "interval": 88,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.75
        },
        "stock": {
            "Tactical Stock": 0.97
        },
        "foregrip": {
            "Haalfgrip": 0.8,
            "Lightweight Grip": 0.92,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.8,
            "3x Scope": 2.8,
            "4x Scope": 4,
            "6x Scope": 6
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "AKM": {
        "ballistic": [
            20,
            30,
            30,
            30,
            42,
            42,
            43,
            43,
            46,
            46,
            46,
            47,
            52,
            52,
            53,
            53,
            52,
            53,
            52,
            53,
            52,
            53,
            52,
            53,
            52,
            53,
            52,
            53,
            53,
            54,
            54,
            54,
            53,
            54,
            54,
            54,
            54,
            54,
            54,
            54,
            54,
            54
        ],
        "interval": 100,
        "attitude": {
            "stand": 1,
            "prone": 0.43,
            "squat": 0.75
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.2
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "AUG": {
        "ballistic": [
            15,
            20,
            20,
            20,
            28,
            28,
            28,
            28,
            38,
            28,
            28,
            28,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34
        ],
        "interval": 86,
        "attitude": {
            "stand": 1,
            "prone": 0.55,
            "squat": 0.8
        },
        "foregrip": {
            "Haalfgrip": 0.82,
            "Lightweight Grip": 0.8,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.8
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        },
        "muzzle": {
            "Compensator AR": 0.86,
            "Flash Hider AR": 0.86,
            "Suppressor AR": 1
        }
    },
    "DP-28": {
        "ballistic": [
            14,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 109,
        "attitude": {
            "stand": 1,
            "prone": 0.04,
            "squat": 0.36
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        }
    },
    "G36C": {
        "ballistic": [
            12,
            22,
            22,
            22,
            32,
            32,
            32,
            32,
            38,
            38,
            38,
            38,
            43,
            43,
            43,
            43,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48
        ],
        "interval": 86,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.75
        },
        "foregrip": {
            "Haalfgrip": 0.75,
            "Lightweight Grip": 0.77,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.72,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "Groza": {
        "ballistic": [
            15,
            24,
            24,
            24,
            30,
            30,
            30,
            30,
            30,
            30,
            30,
            30,
            38,
            38,
            38,
            38,
            38,
            38,
            38,
            38,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40
        ],
        "interval": 80,
        "attitude": {
            "stand": 1,
            "prone": 0.45,
            "squat": 0.67
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.75,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.2
        },
        "muzzle": {
            "Compensator AR": 1,
            "Flash Hider AR": 1,
            "Suppressor AR": 1
        }
    },
    "K2": {
        "ballistic": [
            15,
            25,
            26,
            26,
            32,
            34,
            34,
            34,
            40,
            40,
            40,
            40,
            40,
            40,
            42,
            42,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            57,
            58,
            58,
            58,
            58,
            58
        ],
        "interval": 43,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.75
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.75,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.2
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "M16A4": {
        "ballistic": [
            23,
            19,
            19,
            19,
            28,
            29,
            29,
            29,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            26,
            26,
            26,
            27,
            32,
            33,
            33,
            33
        ],
        "interval": 125,
        "attitude": {
            "stand": 1,
            "prone": 0.6,
            "squat": 0.84
        },
        "stock": {
            "Tactical Stock": 1
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.8,
            "3x Scope": 2.75,
            "4x Scope": 3.75,
            "6x Scope": 5.4
        },
        "muzzle": {
            "Compensator AR": 0.93,
            "Flash Hider AR": 0.93,
            "Suppressor AR": 1
        }
    },
    "M249": {
        "ballistic": [
            10,
            18,
            18,
            18,
            18,
            28,
            28,
            28,
            28,
            28,
            20,
            20,
            20,
            20,
            20,
            14,
            14,
            14,
            14,
            14,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16,
            18,
            18,
            16,
            16,
            16
        ],
        "interval": 93.75,
        "attitude": {
            "stand": 1,
            "prone": 0.25,
            "squat": 0.6
        },
        "stock": {
            "Tactical Stock": 1
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        }
    },
    "M4162": {
        "ballistic": [
            20,
            26,
            32,
            34,
            34,
            34,
            40,
            40,
            40,
            40,
            40,
            40,
            42,
            42,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46
        ],
        "interval": 85,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.75
        },
        "stock": {
            "Tactical Stock": 0.965
        },
        "foregrip": {
            "Haalfgrip": 0.77,
            "Lightweight Grip": 0.77,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "Beryl M762": {
        "ballistic": [
            28,
            38,
            38,
            38,
            42,
            42,
            43,
            43,
            54,
            54,
            55,
            55,
            54,
            54,
            55,
            55,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62,
            62
        ],
        "interval": 86,
        "attitude": {
            "stand": 1,
            "prone": 0.58,
            "squat": 0.83
        },
        "foregrip": {
            "Haalfgrip": 0.8,
            "Lightweight Grip": 0.78,
            "Thumbgrip": 0.93,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.78
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.72,
            "3x Scope": 2.62,
            "4x Scope": 3.62,
            "6x Scope": 5.2
        },
        "muzzle": {
            "Compensator AR": 0.86,
            "Flash Hider AR": 0.86,
            "Suppressor AR": 1
        }
    },
    "MG3": {
        "ballistic": [
            22,
            16,
            16,
            16,
            17,
            18,
            17,
            18,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            11,
            12,
            12,
            12,
            9,
            9,
            9,
            9
        ],
        "interval": 76.25,
        "attitude": {
            "stand": 1,
            "prone": 0.25,
            "squat": 0.45
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.7,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        }
    },
    "Mini14": {
        "ballistic": [
            14,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 125,
        "attitude": {
            "stand": 1,
            "prone": 0.58,
            "squat": 0.73
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.6,
            "2x Scope": 1.8,
            "3x Scope": 2.65,
            "4x Scope": 3.65,
            "6x Scope": 5.3,
            "8x Scope": 7.1
        },
        "muzzle": {
            "Compensator AR": 0.9,
            "Flash Hider AR": 0.9,
            "Suppressor AR": 1,
            "Compensator SR": 0.9,
            "Flash Hider SR": 0.9,
            "Suppressor SR": 1
        }
    },
    "Mk12": {
        "ballistic": [
            24,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 93.8,
        "attitude": {
            "stand": 1,
            "prone": 0.2,
            "squat": 0.74
        },
        "foregrip": {
            "Haalfgrip": 0.92,
            "Lightweight Grip": 0.77,
            "Thumbgrip": 0.96,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.85
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.85,
            "2x Scope": 1.8,
            "3x Scope": 2.75,
            "4x Scope": 3.85,
            "6x Scope": 5.5,
            "8x Scope": 7.35
        },
        "muzzle": {
            "Compensator AR": 0.9,
            "Flash Hider AR": 0.9,
            "Suppressor AR": 1,
            "Compensator SR": 0.9,
            "Flash Hider SR": 0.9,
            "Suppressor SR": 1
        }
    },
    "Mk14": {
        "ballistic": [
            11,
            11,
            11,
            12,
            4,
            4,
            4,
            5,
            12,
            13,
            12,
            13,
            14,
            14,
            14,
            15,
            38,
            38,
            38,
            39,
            40,
            41,
            41,
            41,
            40,
            41,
            41,
            41,
            40,
            41,
            41,
            41,
            40,
            41,
            41,
            41,
            40,
            41,
            41,
            41,
            40,
            41,
            41,
            41,
            60,
            61,
            61,
            61
        ],
        "interval": 22.5,
        "attitude": {
            "stand": 1,
            "prone": 0.17,
            "squat": 0.68
        },
        "stock": {
            "Cheek Pad": 0.73
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.2,
            "2x Scope": 1.7,
            "3x Scope": 2.55,
            "4x Scope": 3.55,
            "6x Scope": 5.2,
            "8x Scope": 6.9
        },
        "muzzle": {
            "Compensator AR": 0.89,
            "Flash Hider AR": 0.89,
            "Suppressor AR": 1,
            "Compensator SR": 0.89,
            "Flash Hider SR": 0.89,
            "Suppressor SR": 1
        }
    },
    "Mk47 Mutant": {
        "ballistic": [
            14,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 125,
        "attitude": {
            "stand": 1,
            "prone": 0.68,
            "squat": 0.85
        },
        "stock": {
            "Tactical Stock": 0.98
        },
        "foregrip": {
            "Haalfgrip": 0.86,
            "Lightweight Grip": 0.68,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.82
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.75,
            "3x Scope": 2.6,
            "4x Scope": 3.65,
            "6x Scope": 5.2
        },
        "muzzle": {
            "Compensator AR": 0.87,
            "Flash Hider AR": 0.87,
            "Suppressor AR": 1
        }
    },
    "MP5K": {
        "ballistic": [
            17,
            17,
            17,
            17,
            17,
            33,
            33,
            33,
            33,
            33,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29,
            29
        ],
        "interval": 83.75,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.65
        },
        "stock": {
            "Tactical Stock": 1
        },
        "foregrip": {
            "Haalfgrip": 0.89,
            "Lightweight Grip": 0.74,
            "Thumbgrip": 0.91,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.74
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.9,
            "3x Scope": 2.9,
            "4x Scope": 4,
            "6x Scope": 5.8
        },
        "muzzle": {
            "Suppressor SMG": 1,
            "Flash Hider SMG": 1,
            "Compensator SMG": 1
        }
    },
    "P90": {
        "ballistic": [
            7,
            14,
            14,
            14,
            14,
            14,
            14,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            15,
            15,
            15,
            15,
            15,
            15,
            15,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            12,
            12,
            12,
            12,
            12
        ],
        "interval": 105,
        "attitude": {
            "stand": 1,
            "prone": 0.65,
            "squat": 0.75
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.8
        }
    },
    "PP-19 Bizon": {
        "ballistic": [
            8,
            16,
            16,
            16,
            16,
            25,
            25,
            25,
            25,
            26,
            23,
            23,
            23,
            23,
            23,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21
        ],
        "interval": 107.5,
        "attitude": {
            "stand": 1,
            "prone": 0.68,
            "squat": 0.78
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.9,
            "3x Scope": 2.9,
            "4x Scope": 4,
            "6x Scope": 5.7
        },
        "muzzle": {
            "Suppressor SMG": 1,
            "Flash Hider SMG": 1,
            "Compensator SMG": 1
        }
    },
    "QBU": {
        "ballistic": [
            11,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 62.5,
        "attitude": {
            "stand": 1,
            "prone": 0.2,
            "squat": 0.74
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.6,
            "2x Scope": 1.8,
            "3x Scope": 2.65,
            "4x Scope": 3.75,
            "6x Scope": 5.3,
            "8x Scope": 7.1
        },
        "muzzle": {
            "Compensator AR": 0.88,
            "Flash Hider AR": 0.88,
            "Suppressor AR": 1,
            "Compensator SR": 0.88,
            "Flash Hider SR": 0.88,
            "Suppressor SR": 1
        }
    },
    "QBZ": {
        "ballistic": [
            14,
            24,
            24,
            24,
            30,
            30,
            30,
            30,
            39,
            39,
            39,
            39,
            47,
            47,
            47,
            48,
            47,
            47,
            47,
            48,
            47,
            47,
            47,
            48,
            47,
            47,
            47,
            47,
            47,
            48,
            47,
            47,
            47,
            47,
            47,
            47,
            47,
            47,
            47,
            47,
            47,
            48
        ],
        "interval": 92,
        "attitude": {
            "stand": 1,
            "prone": 0.5,
            "squat": 0.75
        },
        "foregrip": {
            "Haalfgrip": 0.75,
            "Lightweight Grip": 0.77,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.72,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "SCAR-L": {
        "ballistic": [
            15,
            23,
            23,
            24,
            30,
            30,
            30,
            30,
            38,
            38,
            38,
            39,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43
        ],
        "interval": 96,
        "attitude": {
            "stand": 1,
            "prone": 0.53,
            "squat": 0.75
        },
        "foregrip": {
            "Haalfgrip": 0.77,
            "Lightweight Grip": 0.77,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.72,
            "3x Scope": 2.6,
            "4x Scope": 3.6,
            "6x Scope": 5.1
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1
        }
    },
    "SKS": {
        "ballistic": [
            14,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 125,
        "attitude": {
            "stand": 1,
            "prone": 0.44,
            "squat": 0.64
        },
        "stock": {
            "Cheek Pad": 0.84
        },
        "foregrip": {
            "Haalfgrip": 0.88,
            "Lightweight Grip": 0.65,
            "Thumbgrip": 0.94,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.78
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.3,
            "2x Scope": 1.7,
            "3x Scope": 2.55,
            "4x Scope": 3.55,
            "6x Scope": 5.1,
            "8x Scope": 6.8
        },
        "muzzle": {
            "Compensator AR": 0.88,
            "Flash Hider AR": 0.88,
            "Suppressor AR": 1,
            "Compensator SR": 0.88,
            "Flash Hider SR": 0.88,
            "Suppressor SR": 1
        }
    },
    "SLR": {
        "ballistic": [
            14,
            24,
            24,
            24,
            37,
            37,
            37,
            37,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50
        ],
        "interval": 125,
        "attitude": {
            "stand": 1,
            "prone": 0.43,
            "squat": 0.64
        },
        "stock": {
            "Cheek Pad": 0.7
        },
        "sight": {
            "none": 1,
            "15x Scope": 10.3,
            "2x Scope": 1.7,
            "3x Scope": 2.55,
            "4x Scope": 3.55,
            "6x Scope": 5.1,
            "8x Scope": 6.8
        },
        "muzzle": {
            "Compensator AR": 0.84,
            "Flash Hider AR": 0.84,
            "Suppressor AR": 1,
            "Compensator SR": 0.84,
            "Flash Hider SR": 0.84,
            "Suppressor SR": 1
        }
    },
    "Tommy Gun": {
        "ballistic": [
            10,
            18,
            18,
            18,
            18,
            26,
            26,
            26,
            26,
            39,
            39,
            39,
            39,
            39,
            39,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41
        ],
        "interval": 90,
        "attitude": {
            "stand": 1,
            "prone": 0.58,
            "squat": 0.68
        },
        "foregrip": {
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1
        }
    },
    "UMP45": {
        "ballistic": [
            10,
            19,
            19,
            19,
            26,
            26,
            26,
            28,
            26,
            26,
            26,
            28,
            32,
            32,
            32,
            34,
            30,
            30,
            30,
            32,
            30,
            30,
            30,
            32,
            30,
            30,
            30,
            32,
            30,
            30,
            30,
            30,
            30,
            30,
            30,
            30,
            30
        ],
        "interval": 90,
        "attitude": {
            "stand": 1,
            "prone": 0.64,
            "squat": 0.74
        },
        "foregrip": {
            "Haalfgrip": 0.84,
            "Lightweight Grip": 0.84,
            "Thumbgrip": 0.91,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.77
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.9,
            "3x Scope": 2.9,
            "4x Scope": 4,
            "6x Scope": 5.7
        },
        "muzzle": {
            "Suppressor SMG": 1,
            "Flash Hider SMG": 1,
            "Compensator SMG": 1
        }
    },
    "Micro UZI": {
        "ballistic": [
            8,
            8,
            8,
            8,
            8,
            16,
            16,
            16,
            16,
            16,
            24,
            24,
            24,
            24,
            24,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            31,
            32,
            32,
            32,
            32,
            32,
            32
        ],
        "interval": 60,
        "attitude": {
            "stand": 1,
            "prone": 0.6,
            "squat": 0.75
        },
        "stock": {
            "Folding Stock": 0.7
        },
        "sight": {
            "none": 1
        },
        "muzzle": {
            "Suppressor SMG": 1,
            "Flash Hider SMG": 0.85,
            "Compensator SMG": 0.65
        }
    },
    "Vector": {
        "ballistic": [
            7,
            13,
            13,
            13,
            14,
            24,
            24,
            24,
            24,
            25,
            25,
            25,
            25,
            25,
            25,
            37,
            37,
            37,
            37,
            37,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33
        ],
        "interval": 68.75,
        "attitude": {
            "stand": 1,
            "prone": 0.64,
            "squat": 0.74
        },
        "stock": {
            "Tactical Stock": 0.97
        },
        "foregrip": {
            "Haalfgrip": 0.85,
            "Lightweight Grip": 0.85,
            "Thumbgrip": 0.92,
            "Angled Foregrip": 1,
            "Vertical Foregrip": 0.8
        },
        "sight": {
            "none": 1,
            "2x Scope": 1.9,
            "3x Scope": 2.9,
            "4x Scope": 4,
            "6x Scope": 5.7
        },
        "muzzle": {
            "Suppressor SMG": 1,
            "Flash Hider SMG": 1,
            "Compensator SMG": 1
        }
    },
    "VSS": {
        "ballistic": [
            29,
            29,
            29,
            29,
            86,
            86,
            86,
            86,
            86,
            86,
            86,
            86,
            92,
            92,
            94,
            94,
            106,
            106,
            106,
            106,
            106,
            106
        ],
        "interval": 86,
        "attitude": {
            "stand": 1,
            "prone": 0.57,
            "squat": 0.75
        },
        "stock": {
            "Cheek Pad": 0.77
        },
        "sight": {
            "none": 1
        }
    }

}
